# Generated by Django 4.1.5 on 2023-01-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='category',
        ),
    ]
