# Generated by Django 4.1.5 on 2023-01-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_category_board_user_comment'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='board',
        #     name='category',
        # ),
    ]
