# Generated by Django 4.1.5 on 2023-01-18 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('name', models.CharField(default='', max_length=20)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(choices=[('Male', '남성'), ('Female', '여성')], max_length=10)),
                ('birth', models.DateField(verbose_name='Birth')),
                ('contact', models.CharField(verbose_name='contact',max_length=20)),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),                
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
