# Generated by Django 4.1.5 on 2023-02-01 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('Male', '남성'), ('Female', '여성')], default='', max_length=10)),
                ('birth', models.DateField(default='2023-01-01', null=True, verbose_name='Birth')),
                ('contact', models.CharField(default='', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
